title: Julien Ponge

email: julien@ponge.org

description: >- # this means to ignore newlines until "baseurl:"
  Software engineer, doctor, researcher, lecturer, manager, enthusiast, maker, speaker, (and first and foremost) whatever.

baseurl: "" # the subpath of your site, e.g. /blog

url: "https://julien.ponge.org"
permalink: /blog/:title/

twitter_username: jponge
github_username:  jponge
linkedin_username: JulienPonge
keybase: jponge
rss: rss

header_pages:
  - blog/index.md
  - publications/index.md

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-textile-converter
  - jekyll-redirect-from

exclude:
  - Gemfile
  - Gemfile.lock
  - deploy.sh
  - .ruby-version
  - .gitignore