title: Julien Ponge

email: julien@ponge.org

description: >- # this means to ignore newlines until "baseurl:"
  👋 Hi, I'm Julien!
  I am a long-time software development enthusiast with a career between academia and industry.
  You can call me "Doctor" if you like, but all I can cure is your software, really 😉

baseurl: "" # the subpath of your site, e.g. /blog

url: "https://julien.ponge.org"
permalink: /blog/:title/


twitter_username: jponge
github_username:  jponge
linkedin_username: JulienPonge
instagram_username: jponge
rss: rss

header_pages:
  - blog/index.md
  - publications/index.md

# Build settings
highlighter: pygments
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-textile-converter
  - jekyll-redirect-from

exclude:
  - Gemfile
  - Gemfile.lock
  - deploy.sh
  - .ruby-version
  - .gitignore